//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.08 at 06:04:30 PM CET
//


package org.openstreetmap.josm.data.imagery.types;

import java.util.Calendar;

import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
extends XmlAdapter<String, Calendar>
{


    @Override
    public Calendar unmarshal(String value) {
        return (javax.xml.bind.DatatypeConverter.parseDate(value));
    }

    @Override
    public String marshal(Calendar value) {
        if (value == null)
            return null;
        return (org.openstreetmap.josm.data.imagery.WmsCache.printDate(value));
    }

}
