//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.09 at 07:33:18 PM CET
//


package org.openstreetmap.josm.data.imagery.types;

import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for entry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="entry"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pixelPerDegree" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="east" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="north" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="lastUsed" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="lastModified" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entry", propOrder = {
        "pixelPerDegree",
        "east",
        "north",
        "lastUsed",
        "lastModified",
        "filename"
})
public class EntryType {

    protected double pixelPerDegree;
    protected double east;
    protected double north;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected Calendar lastUsed;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected Calendar lastModified;
    @XmlElement(required = true)
    protected String filename;

    /**
     * Gets the value of the pixelPerDegree property.
     *
     */
    public double getPixelPerDegree() {
        return pixelPerDegree;
    }

    /**
     * Sets the value of the pixelPerDegree property.
     *
     */
    public void setPixelPerDegree(double value) {
        this.pixelPerDegree = value;
    }

    /**
     * Gets the value of the east property.
     *
     */
    public double getEast() {
        return east;
    }

    /**
     * Sets the value of the east property.
     *
     */
    public void setEast(double value) {
        this.east = value;
    }

    /**
     * Gets the value of the north property.
     *
     */
    public double getNorth() {
        return north;
    }

    /**
     * Sets the value of the north property.
     *
     */
    public void setNorth(double value) {
        this.north = value;
    }

    /**
     * Gets the value of the lastUsed property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public Calendar getLastUsed() {
        return lastUsed;
    }

    /**
     * Sets the value of the lastUsed property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastUsed(Calendar value) {
        this.lastUsed = value;
    }

    /**
     * Gets the value of the lastModified property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public Calendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastModified(Calendar value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the filename property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFilename(String value) {
        this.filename = value;
    }

}
