//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.09 at 07:33:18 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://josm.openstreetmap.de/wms-cache", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openstreetmap.josm.data.imagery.types;
