/* Generated By:JavaCC: Do not edit this line. MapCSSParserConstants.java */
package org.openstreetmap.josm.gui.mappaint.mapcss.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MapCSSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENT = 1;
  /** RegularExpression Id. */
  int UINT = 2;
  /** RegularExpression Id. */
  int UFLOAT = 3;
  /** RegularExpression Id. */
  int STRING = 4;
  /** RegularExpression Id. */
  int H = 5;
  /** RegularExpression Id. */
  int HEXCOLOR = 6;
  /** RegularExpression Id. */
  int S = 7;
  /** RegularExpression Id. */
  int STAR = 8;
  /** RegularExpression Id. */
  int SLASH = 9;
  /** RegularExpression Id. */
  int LBRACE = 10;
  /** RegularExpression Id. */
  int RBRACE = 11;
  /** RegularExpression Id. */
  int LSQUARE = 12;
  /** RegularExpression Id. */
  int RSQUARE = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 16;
  /** RegularExpression Id. */
  int LESS_EQUAL = 17;
  /** RegularExpression Id. */
  int GREATER = 18;
  /** RegularExpression Id. */
  int LESS = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int EXCLAMATION = 21;
  /** RegularExpression Id. */
  int EXCLAMATION_EQUAL = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int DCOLON = 24;
  /** RegularExpression Id. */
  int SEMICOLON = 25;
  /** RegularExpression Id. */
  int COMMA = 26;
  /** RegularExpression Id. */
  int PIPE = 27;
  /** RegularExpression Id. */
  int PIPE_Z = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int AMPERSAND = 31;
  /** RegularExpression Id. */
  int QUESTION = 32;
  /** RegularExpression Id. */
  int COMMENT_START = 33;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 34;
  /** RegularExpression Id. */
  int COMMENT_END = 35;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IDENT>",
    "<UINT>",
    "<UFLOAT>",
    "<STRING>",
    "<H>",
    "<HEXCOLOR>",
    "<S>",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"!\"",
    "\"!=\"",
    "\":\"",
    "\"::\"",
    "\";\"",
    "\",\"",
    "\"|\"",
    "\"|z\"",
    "\"+\"",
    "\"-\"",
    "\"&\"",
    "\"?\"",
    "\"/*\"",
    "<UNEXPECTED_CHAR>",
    "\"*/\"",
    "<token of kind 36>",
  };

}
